In [1]:
from helper import *
pd.set_option('display.precision', 2)

import warnings
from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

from ipynb.fs.full.functions import project

In [2]:
file = 'Testing/April 16.csv'

# BO5s

In [3]:
df = pd.read_csv(file)
df = df[df['Stat type'] == 'MAPS 1-3 Kills'].sort_values('Team').drop(['Added', 'Updated'], axis=1)
df.Name[df.Name=='Glory'] = 'Glory2'

In [4]:
project('TW', 'CES', 2, 1, df)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,Glory2,MID,TW,CES,MAPS 1-3 Kills,9.0,10.47,1.47
1,Vit,BOT,TW,CES,MAPS 1-3 Kills,13.5,16.56,3.06
2,Yado,MID,CES,TW,MAPS 1-3 Kills,8.0,8.54,0.54
3,Artemis,BOT,CES,TW,MAPS 1-3 Kills,13.0,12.12,-0.88

PROJECTIONS BASED ON:  TW 2-1 CES

# BO3s

In [5]:
df = pd.read_csv(file)
df = df[df['Stat type'] == 'MAPS 1-2 Kills'].sort_values('Team').drop(['Added', 'Updated'], axis=1)

In [6]:
project('G2', 'KOI', 2, 0, df)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,Hans sama,BOT,G2,KOI,MAPS 1-2 Kills,10.0,11.90,1.90
1,Caps,MID,G2,KOI,MAPS 1-2 Kills,8.0,10.00,2.00
2,BrokenBlade,TOP,G2,KOI,MAPS 1-2 Kills,8.0,9.43,1.43
3,Yike,JNG,G2,KOI,MAPS 1-2 Kills,8.5,9.52,1.02
4,Larssen,MID,KOI,G2,MAPS 1-2 Kills,6.0,4.38,-1.62
5,Comp,BOT,KOI,G2,MAPS 1-2 Kills,6.5,4.25,-2.25
6,Malrang,JNG,KOI,G2,MAPS 1-2 Kills,3.5,2.50,-1.00
7,Szygenda,TOP,KOI,G2,MAPS 1-2 Kills,4.0,2.75,-1.25

PROJECTIONS BASED ON:  G2 2-0 KOI

In [7]:
project('AST', 'MAD', 2, 0, df)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,113,JNG,AST,MAD,MAPS 1-2 Kills,5.0,5.00,0.00
1,LIDER,MID,AST,MAD,MAPS 1-2 Kills,8.5,10.25,1.75
2,Finn,TOP,AST,MAD,MAPS 1-2 Kills,5.5,5.71,0.21
3,Kobbe,BOT,AST,MAD,MAPS 1-2 Kills,10.5,12.29,1.79
4,Nisqy,MID,MAD,AST,MAPS 1-2 Kills,6.5,4.88,-1.62
5,Chasy,TOP,MAD,AST,MAPS 1-2 Kills,5.5,3.38,-2.12
6,Carzzy,BOT,MAD,AST,MAPS 1-2 Kills,8.5,5.00,-3.50
7,Elyoya,JNG,MAD,AST,MAPS 1-2 Kills,6.0,3.75,-2.25

PROJECTIONS BASED ON:  AST 2-0 MAD

In [8]:
project('AST', 'MAD', 1, 1, df)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,113,JNG,AST,MAD,MAPS 1-2 Kills,5.0,3.75,-1.25
1,LIDER,MID,AST,MAD,MAPS 1-2 Kills,8.5,7.29,-1.21
2,Finn,TOP,AST,MAD,MAPS 1-2 Kills,5.5,4.73,-0.77
3,Kobbe,BOT,AST,MAD,MAPS 1-2 Kills,10.5,8.58,-1.92
4,Nisqy,MID,MAD,AST,MAPS 1-2 Kills,6.5,6.22,-0.28
5,Chasy,TOP,MAD,AST,MAPS 1-2 Kills,5.5,5.90,0.40
6,Carzzy,BOT,MAD,AST,MAPS 1-2 Kills,8.5,9.64,1.14
7,Elyoya,JNG,MAD,AST,MAPS 1-2 Kills,6.0,6.23,0.23

PROJECTIONS BASED ON:  AST 1-1 MAD