In [1]:
from helper import *
pd.set_option('display.precision', 2)

import warnings
from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

from ipynb.fs.full.functions import project

In [2]:
file = 'Testing/April 16.csv'

In [3]:
favorites = pd.DataFrame()

# BO5s

In [4]:
df = pd.read_csv(file)
df = df[df['Stat type'] == 'MAPS 1-3 Kills'].sort_values('Team').drop(['Added', 'Updated'], axis=1)
df.Name[df.Name=='Glory'] = 'Glory2'

In [5]:
proj = project('TW', 'CES', 2, 1, df)
favorites = favorites.append(proj)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,Glory2,MID,TW,CES,MAPS 1-3 Kills,9.0,10.63,1.63
1,Vit,BOT,TW,CES,MAPS 1-3 Kills,13.5,15.02,1.52
2,Yado,MID,CES,TW,MAPS 1-3 Kills,8.0,7.79,-0.21
3,Artemis,BOT,CES,TW,MAPS 1-3 Kills,13.0,12.43,-0.57

PROJECTIONS BASED ON: TW 2-1 CES

# BO3s

In [6]:
df = pd.read_csv(file)
df = df[df['Stat type'] == 'MAPS 1-2 Kills'].sort_values('Team').drop(['Added', 'Updated'], axis=1)

In [7]:
proj = project('G2', 'KOI', 2, 0, df)
favorites = favorites.append(proj)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,Hans sama,BOT,G2,KOI,MAPS 1-2 Kills,10.0,11.52,1.52
1,Caps,MID,G2,KOI,MAPS 1-2 Kills,8.0,9.44,1.44
2,BrokenBlade,TOP,G2,KOI,MAPS 1-2 Kills,8.0,8.80,0.80
3,Yike,JNG,G2,KOI,MAPS 1-2 Kills,8.5,10.80,2.30
4,Larssen,MID,KOI,G2,MAPS 1-2 Kills,6.0,4.42,-1.58
5,Comp,BOT,KOI,G2,MAPS 1-2 Kills,6.5,3.89,-2.61
6,Malrang,JNG,KOI,G2,MAPS 1-2 Kills,3.5,2.63,-0.87
7,Szygenda,TOP,KOI,G2,MAPS 1-2 Kills,4.0,2.63,-1.37

PROJECTIONS BASED ON: G2 2-0 KOI

In [8]:
proj = project('AST', 'MAD', 1, 1, df)
favorites = favorites.append(proj)

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,113,JNG,AST,MAD,MAPS 1-2 Kills,5.0,3.91,-1.09
1,LIDER,MID,AST,MAD,MAPS 1-2 Kills,8.5,7.29,-1.21
2,Finn,TOP,AST,MAD,MAPS 1-2 Kills,5.5,4.80,-0.70
3,Kobbe,BOT,AST,MAD,MAPS 1-2 Kills,10.5,8.85,-1.65
4,Nisqy,MID,MAD,AST,MAPS 1-2 Kills,6.5,7.20,0.70
5,Chasy,TOP,MAD,AST,MAPS 1-2 Kills,5.5,5.84,0.34
6,Carzzy,BOT,MAD,AST,MAPS 1-2 Kills,8.5,8.30,-0.20
7,Elyoya,JNG,MAD,AST,MAPS 1-2 Kills,6.0,4.97,-1.03

PROJECTIONS BASED ON: AST 1-1 MAD

# Favorite Plays

In [9]:
favorites

,Name,Position,Team,Opponent Team,Stat type,Projection,Model Proj,Difference
0,Glory2,MID,TW,CES,MAPS 1-3 Kills,9.0,10.63,1.63
1,Vit,BOT,TW,CES,MAPS 1-3 Kills,13.5,15.02,1.52
0,Hans sama,BOT,G2,KOI,MAPS 1-2 Kills,10.0,11.52,1.52
3,Yike,JNG,G2,KOI,MAPS 1-2 Kills,8.5,10.80,2.30
4,Larssen,MID,KOI,G2,MAPS 1-2 Kills,6.0,4.42,-1.58
5,Comp,BOT,KOI,G2,MAPS 1-2 Kills,6.5,3.89,-2.61
3,Kobbe,BOT,AST,MAD,MAPS 1-2 Kills,10.5,8.85,-1.65